### ISSUE TITLE
Allow cursor movement in only one axis

### ISSUE THREAD

**Issue by KazDragon** [KazDragon/terminalpp#175]
Use-Case: a command line application with a progress bar.  For this, it is necessary to move to a fixed point (possibly character 0) on the current line, even though the current Y position is unknown.

**Comment by KazDragon** [comment]
Note: VT100 provides horizontal absolute movement in CHA (Cursor Character Absolute: CSI x G), and vertical movement in VPA (Line Position Absolute: CSI y d).

**Comment by LoganDark** [comment]
CR usually the cursor to the beginning of the current line. You can then move the cursor right from there.

I say usually because the spec is ridiculous about its behavior, but usually, yeah it just moves the cursor to the beginning of the line.
