### ISSUE TITLE
Add a user defined literal for single elements

### ISSUE THREAD

**Issue by KazDragon** [KazDragon/terminalpp#189]
Currenly, a user must do something like "\\U+2502"_ets[0] to get a one character literal.  

This is more typing than strictly necessary (could be, e.g. "U+2502"_ete) but also produces a string that is not constexpr.  A version that produces only one element could be constexpr.

**Comment by LoganDark** [comment]
`L'\u2502'_ets`/`_ete`?

**Comment by KazDragon** [comment]
Could possibly do that, but there's the encoding for other attributes and character sets as well.  E.g.

    "\\[3\\]1\\i>\\U263A"_ete // (yellow foreground red background bold smiley)

should be completely parseable at compile-time.

**Comment by LoganDark** [comment]
Oh wait, nevermind. I'm dumb, I forgot that you need to put attributes/whatever in it (requiring a string rather than char literal)
