### ISSUE TITLE
Header-only "mode"

### ISSUE THREAD

**Issue by LoganDark** [KazDragon/terminalpp#191]
Header-only just means that there's some file you can `#include` to bring the entire library into your project rather than requiring a linking step. Maybe there's the possibility of some file that includes all the `.cpp` files so you can just drop in an `#include` and use Terminal++.

**Comment by KazDragon** [comment]
> > I think the best course of action for you if you still want to pursue this course is to copy the .hpp and .cpp files from the library into your project flat. That is, without any subdirectories. Then, change all of the #includes to be flat as well.

> Which file(s) should I #include? I'll look into it...

From main.cpp, whichever files you would have included before.  Probably #include "ansi_terminal.hpp"

**Comment by LoganDark** [comment]
In `core.cpp`...
![image](https://user-images.githubusercontent.com/4723091/49818820-924f7480-fd28-11e8-86cb-91d3cfa322ba.png)
What is `export.hpp`?

**Comment by LoganDark** [comment]
Oh, nevermind, looked in CMakeLists and it seems to be an 'export header'.

**Comment by LoganDark** [comment]
Welp, I did it.

https://github.com/LoganDark/terminalpp/blob/0275fb696d805941edf9e0deee745682a68f893b/terminalpp.hpp#L5-L36

Works with this code:

```cpp
#include <iostream>

#include "terminalpp/terminalpp.hpp"

namespace tpp = terminalpp;

int main() {
	tpp::ansi_terminal term;
	tpp::screen        screen;
	tpp::canvas        canvas({80, 24});
	tpp::element       elem('x');

	elem.attribute_.background_colour_ = tpp::greyscale_colour(12);

	tpp::extent size = canvas.size();

	for (tpp::coordinate_type y = 0; y < size.height; y++) {
		for (tpp::coordinate_type x = 0; x < size.width; x++) {
			canvas[x][y] = elem;
		}
	}

	std::cout << screen.draw(term, canvas);
}
```

Ty!

**Comment by KazDragon** [comment]
Nice.
